#!/usr/bin/env python3
"""Maintain CHANGELOG.md (Keep a Changelog format).

The release-prep workflow (.github/workflows/prepare-release.yml) calls:

    python scripts/changelog.py roll 0.4.0            # date = today (UTC)
    python scripts/changelog.py roll 0.4.0 --date 2026-06-01

which moves everything under ``## [Unreleased]`` into a new dated
``## [0.4.0] - YYYY-MM-DD`` section and leaves a fresh, empty Unreleased
block at the top. The rolled file is committed as part of the
``chore: release vX.Y.Z`` PR, so the changelog goes through the same
branch ruleset (PR + checks) as any other change — nothing pushes to
``main`` directly.

Contributors do NOT edit this file in feature PRs. They drop a **news fragment** in
``changelog.d/<issue>.<kind>.md`` (#2322); ``collate`` folds those into
``## [Unreleased]`` at release time, immediately before ``roll``. Every PR used to write
to the same three lines under ``[Unreleased]``, so two PRs in flight conflicted by
construction and a stack of N cost O(N) serial merges — distinct filenames have nothing
to 3-way merge.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
from pathlib import Path

CHANGELOG = Path(__file__).parent.parent / "CHANGELOG.md"
# The marketing site's /changelog page reads this — DERIVED from CHANGELOG.md so it
# is **curated** (clean, user-facing blurbs — a different audience than CHANGELOG.md's
# detailed dev notes). It is NOT auto-derived from CHANGELOG.md (that produced verbose,
# jargon-y entries). Instead: `scaffold` drafts a *concise* entry per new release (bullet
# titles only) for a human to polish, and `missing_versions` guards against staleness.
MARKETING_JSON = Path(__file__).parent.parent / "sites" / "marketing" / "data" / "changelog.json"

_UNRELEASED_HEADING = "## [Unreleased]"

FRAGMENTS_DIR = Path(__file__).parent.parent / "changelog.d"

# Keep a Changelog's kinds, plus the `Docs` bucket this repo already uses. Order is the
# order they render under [Unreleased].
_KINDS = ("added", "changed", "fixed", "removed", "deprecated", "security", "docs")
# `<anything>.<kind>.md` — the stem before the kind is free-form (issue no., PR no., a
# slug) since it only has to be unique, which is the entire point.
_FRAGMENT_RE = re.compile(r"^(?P<stem>.+)\.(?P<kind>[a-z]+)\.md$")


def _strip_md(s: str) -> str:
    """Markdown → plain text (the marketing page renders plain text); drop ADR refs."""
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)  # **bold** → bold
    s = re.sub(r"`([^`]+)`", r"\1", s)  # `code` → code
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)  # [text](url) → text
    s = re.sub(r"\s*\(ADR[^)]*\)", "", s)  # drop "(ADR 0026)"
    return re.sub(r"\s+", " ", s).strip()


def _section(text: str, version: str) -> tuple[str | None, str]:
    """(date, body) for ``## [version] - DATE`` — (None, "") if absent."""
    m = re.search(rf"^## \[{re.escape(version)}\] - (\S+)[ \t]*$", text, re.MULTILINE)
    if not m:
        return None, ""
    start = m.end()
    nxt = re.search(r"^## \[", text[start:], re.MULTILINE)
    return m.group(1), (text[start : start + nxt.start()] if nxt else text[start:])


def _titles(body: str) -> list[str]:
    """Concise draft summaries: each top-level bullet's **bold lead** (or first clause).

    A bullet's continuation lines are folded in before extraction, so a bold lead that
    wraps across lines (``- **A long lead\\n  that wraps.** rest``) is captured whole
    instead of leaving a stray ``**`` (the v0.47/v0.53 marketing-changelog glitch).
    """
    out: list[str] = []
    chunk: list[str] | None = None  # the current top-level bullet's lines

    def flush() -> None:
        if not chunk:
            return
        text = re.sub(r"\s+", " ", " ".join(chunk)).strip()
        bold = re.match(r"\*\*(.+?)\*\*", text)
        title = bold.group(1) if bold else re.split(r"\s+[—-]\s+|\. ", text, 1)[0]
        out.append(_strip_md(title))

    for line in body.splitlines():
        m = re.match(r"^- +(.*)$", line)  # a new TOP-LEVEL bullet (no leading indent)
        if m:
            flush()
            chunk = [m.group(1)]
        elif chunk is not None:
            s = line.strip()
            if not s or s.startswith("- ") or line.startswith("#"):
                flush()  # blank / nested bullet / heading → the bullet (and its lead) ends
                chunk = None
            else:
                chunk.append(s)  # an indented continuation line of the current bullet
    flush()
    return out


def dated_versions(text: str) -> list[str]:
    """All released versions (``X.Y.Z``) with a dated section in CHANGELOG.md."""
    return re.findall(r"^## \[(\d+\.\d+\.\d+)\] - ", text, re.MULTILINE)


def _vtuple(v: str) -> tuple[int, ...]:
    return tuple(int(x) for x in v.lstrip("v").split("."))


def missing_versions() -> list[str]:
    """Released versions inside the curated range with content but no changelog.json entry.

    The marketing changelog only goes back to a curated floor (~v0.16), so we don't
    demand ancient history — we catch a *forgotten new release* (the original
    'stuck at 0.21' bug): any version at or above the oldest curated entry that's
    missing. An **empty** release (no ``[Unreleased]`` bullets → an empty section) is
    intentionally omitted from /changelog, so it's not flagged as missing.
    """
    have = {e["version"] for e in json.loads(MARKETING_JSON.read_text(encoding="utf-8"))}
    if not have:
        return []
    floor = min(_vtuple(v) for v in have)
    text = CHANGELOG.read_text(encoding="utf-8")
    return [
        f"v{v}"
        for v in dated_versions(text)
        if _vtuple(v) >= floor and f"v{v}" not in have and _titles(_section(text, v)[1])
    ]


def scaffold(version: str) -> bool:
    """Prepend a CONCISE draft entry (bullet titles) for *version* to changelog.json IF
    absent. Preserves existing curated entries (idempotent); returns True if it added one.
    A human polishes the wording — this just guarantees no version is missing."""
    entries = json.loads(MARKETING_JSON.read_text(encoding="utf-8"))
    vtag = f"v{version}"
    if any(e["version"] == vtag for e in entries):
        return False
    date, body = _section(CHANGELOG.read_text(encoding="utf-8"), version)
    if date is None:
        raise ValueError(f"no '## [{version}]' section in CHANGELOG.md")
    changes = _titles(body)
    if not changes:
        # Empty release (the PRs added no `[Unreleased]` bullets) → omit it from the
        # marketing changelog rather than emit a bare version+date line. Add a bullet
        # under `[Unreleased]` in your PR for the release to appear on /changelog.
        return False
    entries.insert(0, {"version": vtag, "date": date, "changes": changes})
    MARKETING_JSON.write_text(json.dumps(entries, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return True


def notes(version: str) -> str:
    """Return the changelog section body for *version* (markdown), or '' if absent/empty.

    Fed to the desktop updater-manifest job so the in-app UpdateNotice shows the curated
    CHANGELOG section instead of raw commit subjects. Empty output is the caller's signal
    to fall back (GitHub release body → placeholder) — e.g. a patch with no bullets.

    Searches the current ``CHANGELOG.md`` first, then the monthly archives (#2437), so
    rebuilding an *older* desktop release still finds that version's notes after its
    section has rolled off the root file.
    """
    for path in [CHANGELOG, *_archive_files()]:
        if not path.exists():
            continue
        date, body = _section(path.read_text(encoding="utf-8"), version)
        if date is not None:  # the section lives here (body may be empty → '' → fallback)
            return body.strip()
    return ""


# ── Monthly archives (#2437) ─────────────────────────────────────────────────
#
# CHANGELOG.md grows without bound (600 KB+ before this landed), so most reads only
# want ``[Unreleased]`` + the current month. ``archive`` moves older dated sections —
# VERBATIM, no regeneration from git — into ``CHANGELOG-YYYY-MM.md`` (or a one-time
# ``CHANGELOG-THROUGH-YYYY-MM.md`` bulk) next to the root file, and maintains
# cross-links. ``collate``/``roll`` still write ONLY the root file; ``notes`` reads
# the archives too. Rollover is a documented manual chore, not a scheduled workflow.

_ARCHIVE_INDEX_START = "<!-- archive-index -->"
_ARCHIVE_INDEX_END = "<!-- /archive-index -->"


def _archive_files() -> list[Path]:
    """Every archive file next to CHANGELOG.md (``CHANGELOG-*.md``), sorted by name."""
    return sorted(CHANGELOG.parent.glob("CHANGELOG-*.md"))


def _archive_label(name: str) -> str:
    """A human label for an archive filename, for links/headers.

    ``CHANGELOG-THROUGH-2026-07.md`` → ``through 2026-07``; ``CHANGELOG-2026-08.md`` → ``2026-08``.
    """
    stem = name
    if stem.startswith("CHANGELOG-"):
        stem = stem[len("CHANGELOG-") :]
    if stem.endswith(".md"):
        stem = stem[: -len(".md")]
    return f"through {stem[len('THROUGH-'):]}" if stem.startswith("THROUGH-") else stem


def _split_sections(text: str) -> list[tuple[str, str | None, str | None, str]]:
    """``[(kind, version, date, chunk), …]`` for the header + every ``## [...]`` section.

    ``kind`` ∈ {``header``, ``unreleased``, ``version``}. Each ``chunk`` is the exact
    substring from its heading to the next (the header chunk is everything before the
    first heading), so ``"".join(chunks) == text`` — the split is lossless.
    """
    heads = list(re.finditer(r"^## \[([^\]]+)\](?: - (\S+))?[ \t]*$", text, re.MULTILINE))
    if not heads:
        return [("header", None, None, text)]
    out: list[tuple[str, str | None, str | None, str]] = [("header", None, None, text[: heads[0].start()])]
    for i, m in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        chunk = text[m.start() : end]
        if m.group(1) == "Unreleased":
            out.append(("unreleased", None, None, chunk))
        else:
            out.append(("version", m.group(1), m.group(2), chunk))
    return out


def _archive_index_block() -> str:
    """The marker-delimited "Older releases" index, regenerated from the archive files
    on disk — deterministic, so re-running never drifts."""
    files = _archive_files()
    if not files:
        return ""
    links = ", ".join(f"[{_archive_label(p.name)}]({p.name})" for p in files)
    return f"{_ARCHIVE_INDEX_START}\n> \U0001f4da **Older releases** are archived: {links}.\n{_ARCHIVE_INDEX_END}\n"


def _set_archive_index(text: str) -> str:
    """Insert/replace the archive-index block immediately above ``## [Unreleased]``."""
    text = re.sub(
        re.escape(_ARCHIVE_INDEX_START) + r".*?" + re.escape(_ARCHIVE_INDEX_END) + r"\n?",
        "",
        text,
        flags=re.DOTALL,
    )
    block = _archive_index_block()
    if block:
        m = re.search(r"^## \[Unreleased\]", text, re.MULTILINE)
        if m:
            text = text[: m.start()] + block + "\n" + text[m.start() :]
    return re.sub(r"\n{3,}", "\n\n", text)


def archive(before: str, out_name: str, title: str | None = None) -> tuple[int, Path]:
    """Move release sections dated < ``before`` (``YYYY-MM-DD``) out of CHANGELOG.md into
    ``out_name``. Returns ``(moved_count, out_path)``.

    Sections are moved VERBATIM and in order (no regeneration). Idempotent: re-running
    moves nothing because the sections are no longer in the root. If ``out_name`` already
    exists its sections are preserved and de-duped. The root archive index is regenerated.
    """
    out_path = CHANGELOG.parent / out_name
    sections = _split_sections(CHANGELOG.read_text(encoding="utf-8"))
    kept: list[str] = []
    moved: list[tuple[str, str]] = []
    for kind, version, date, chunk in sections:
        if kind == "version" and date is not None and date < before:
            moved.append((version, chunk))  # type: ignore[arg-type]
        else:
            kept.append(chunk)
    if not moved:
        return 0, out_path

    moved_versions = {v for v, _ in moved}
    existing = ""
    if out_path.exists():
        for kind, version, _date, chunk in _split_sections(out_path.read_text(encoding="utf-8")):
            if kind == "version" and version not in moved_versions:
                existing += chunk
    header = (
        f"# Changelog — archived releases ({title or _archive_label(out_name)})\n\n"
        "Historical release notes moved out of [CHANGELOG.md](CHANGELOG.md) to keep the current "
        "file small (#2437). See **[CHANGELOG.md](CHANGELOG.md)** for `[Unreleased]` and the "
        "current releases.\n\n"
    )
    archive_text = re.sub(r"\n{3,}", "\n\n", header + "".join(c for _, c in moved) + existing).rstrip("\n") + "\n"
    out_path.write_text(archive_text, encoding="utf-8")

    new_root = re.sub(r"\n{3,}", "\n\n", _set_archive_index("".join(kept))).rstrip("\n") + "\n"
    CHANGELOG.write_text(new_root, encoding="utf-8")
    return len(moved), out_path


def read_fragments(directory: Path | None = None) -> tuple[dict[str, list[str]], list[Path]]:
    """``({kind: [body, …]}, [paths])`` for every fragment in ``changelog.d/``.

    Sorted by filename so collation order is deterministic (a release diff should not
    reshuffle just because the filesystem felt like it). An unrecognised ``<kind>`` is a
    hard error, not a silent drop: a fragment quietly filed under the wrong heading — or
    not filed at all — is exactly the release-notes-lie this whole gate exists to stop.
    """
    directory = directory or FRAGMENTS_DIR
    buckets: dict[str, list[str]] = {}
    used: list[Path] = []
    if not directory.is_dir():
        return buckets, used
    bad: list[str] = []
    for path in sorted(directory.iterdir()):
        if path.name in ("README.md", ".gitkeep") or path.is_dir():
            continue
        m = _FRAGMENT_RE.match(path.name)
        if not m:
            bad.append(f"{path.name} (expected <name>.<kind>.md)")
            continue
        kind = m.group("kind").lower()
        if kind not in _KINDS:
            bad.append(f"{path.name} (unknown kind {kind!r}; expected one of {', '.join(_KINDS)})")
            continue
        body = path.read_text(encoding="utf-8").strip("\n")
        if body.strip():
            buckets.setdefault(kind, []).append(body)
            used.append(path)
    if bad:
        raise ValueError("unusable changelog fragment(s): " + "; ".join(bad))
    return buckets, used


def lint_fragments(paths: list[Path]) -> list[str]:
    """Problems with each fragment, one human-readable line each. Empty ⇒ all usable.

    The PR gate used to check only that a fragment **exists**, which is a weaker property
    than the one that matters: that it will still be there in the release notes (#2600).
    A fragment whose text isn't a top-level ``- `` bullet passes that check, collates into
    ``[Unreleased]`` fine, and then contributes nothing to the marketing changelog —
    ``scaffold`` derives its entry from :func:`_titles`, which only sees top-level bullets.
    If no fragment in the release parses, ``scaffold`` treats the version as empty and
    omits it from ``/changelog`` altogether. That failure surfaces days later to whoever
    cuts the release, nowhere near the PR that caused it.

    Checks the same three things the collator does — name shape, known kind, non-empty —
    plus the one it doesn't: that the body yields at least one title.
    """
    problems: list[str] = []
    for path in paths:
        if path.name in ("README.md", ".gitkeep"):
            continue
        m = _FRAGMENT_RE.match(path.name)
        if not m:
            problems.append(f"{path.name}: expected <issue-or-pr>.<kind>.md")
            continue
        kind = m.group("kind").lower()
        if kind not in _KINDS:
            problems.append(f"{path.name}: unknown kind {kind!r} — expected one of {', '.join(_KINDS)}")
            continue
        try:
            body = path.read_text(encoding="utf-8")
        except OSError as exc:
            problems.append(f"{path.name}: unreadable ({exc})")
            continue
        if not body.strip():
            problems.append(f"{path.name}: empty")
            continue
        if not _titles(body):
            problems.append(
                f"{path.name}: no top-level '- ' bullet, so this text would be dropped from the "
                f"release notes. Start each entry with '- ' (see changelog.d/README.md)."
            )
    return problems


def collate(text: str, buckets: dict[str, list[str]]) -> str:
    """Fold fragment ``buckets`` into ``text``'s ``[Unreleased]`` section.

    Entries merge INTO an existing ``### Fixed`` when one is already there rather than
    appending a second one — duplicate headings inside a single Unreleased section were
    the other half of the shared-anchor problem (#2322), and they had to be consolidated
    by hand every cycle.
    """
    if not buckets:
        return text
    m = re.search(r"^## \[Unreleased\][ \t]*\n", text, re.MULTILINE)
    if not m:
        raise ValueError("no '## [Unreleased]' section in CHANGELOG.md")
    start = m.end()
    nxt = re.search(r"^## \[", text[start:], re.MULTILINE)
    end = start + nxt.start() if nxt else len(text)
    body = text[start:end].strip("\n")

    for kind in _KINDS:
        entries = buckets.get(kind)
        if not entries:
            continue
        heading = f"### {kind.capitalize()}"
        addition = "\n\n".join(entries)
        hm = re.search(rf"^{re.escape(heading)}[ \t]*$", body, re.MULTILINE)
        if hm:
            # Append to the existing bucket, just before the next ### (or the end).
            after = body[hm.end():]
            nh = re.search(r"^### ", after, re.MULTILINE)
            cut = hm.end() + (nh.start() if nh else len(after))
            body = body[:cut].rstrip("\n") + "\n" + addition + "\n\n" + body[cut:].lstrip("\n")
        else:
            body = (body + "\n\n" if body else "") + heading + "\n" + addition

    rebuilt = f"{text[: m.start()]}{_UNRELEASED_HEADING}\n\n{body.strip(chr(10))}\n\n{text[end:]}"
    return re.sub(r"\n{3,}", "\n\n", rebuilt)


def roll(text: str, version: str, date: str) -> str:
    """Return *text* with the Unreleased section promoted to ``[version] - date``.

    Raises ``ValueError`` if there's no Unreleased heading.
    """
    m = re.search(r"^## \[Unreleased\][ \t]*\n", text, re.MULTILINE)
    if not m:
        raise ValueError("no '## [Unreleased]' section in CHANGELOG.md")

    start = m.end()
    # The Unreleased body runs until the next version heading (or EOF / footer).
    nxt = re.search(r"^## \[", text[start:], re.MULTILINE)
    end = start + nxt.start() if nxt else len(text)
    body = text[start:end].strip("\n")

    section = f"## [{version}] - {date}\n"
    if body:
        section += f"\n{body}\n"

    before = text[: m.start()]
    after = text[end:]
    rebuilt = f"{before}{_UNRELEASED_HEADING}\n\n{section}\n{after}"
    # Normalize runs of blank lines introduced by the splice.
    return re.sub(r"\n{3,}", "\n\n", rebuilt)


def main() -> None:
    parser = argparse.ArgumentParser(description="Maintain CHANGELOG.md")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_roll = sub.add_parser("roll", help="promote Unreleased to a dated version section")
    p_roll.add_argument("version", help="version being released, e.g. 0.4.0")
    p_roll.add_argument(
        "--date",
        default=datetime.datetime.now(datetime.timezone.utc).date().isoformat(),
        help="release date (YYYY-MM-DD); defaults to today (UTC)",
    )
    p_sc = sub.add_parser(
        "scaffold",
        help="prepend a concise DRAFT changelog.json entry for a version (curated content stays)",
    )
    p_sc.add_argument("version", help="version released, e.g. 0.26.0")
    p_notes = sub.add_parser(
        "notes",
        help="print the CHANGELOG.md section body for a version (the desktop in-app updater notes)",
    )
    p_notes.add_argument("version", help="version released, e.g. 0.60.0")
    sub.add_parser("check", help="fail if any released version is missing from changelog.json")
    p_lint = sub.add_parser(
        "lint-fragments",
        help="fail if a changelog.d fragment wouldn't survive collation (the PR gate's check)",
    )
    p_lint.add_argument(
        "paths",
        nargs="*",
        help="fragment paths to check; default: every fragment in changelog.d/",
    )
    p_col = sub.add_parser(
        "collate", help="fold changelog.d/ fragments into [Unreleased], then delete them"
    )
    p_col.add_argument(
        "--keep", action="store_true", help="leave the fragment files in place (dry-run-ish)"
    )
    p_arc = sub.add_parser(
        "archive",
        help="move release sections dated before --before into a dated archive file (#2437)",
    )
    p_arc.add_argument("--before", required=True, help="move sections dated before this YYYY-MM-DD")
    p_arc.add_argument("--out", required=True, help="archive filename, e.g. CHANGELOG-THROUGH-2026-07.md")
    p_arc.add_argument("--title", default=None, help="human label for the archive header + index link")
    args = parser.parse_args()

    if args.cmd == "collate":
        buckets, used = read_fragments()
        if not used:
            print("no changelog fragments to collate")
            return
        CHANGELOG.write_text(collate(CHANGELOG.read_text(encoding="utf-8"), buckets), encoding="utf-8")
        if not args.keep:
            for path in used:
                path.unlink()
        total = sum(len(v) for v in buckets.values())
        kinds = ", ".join(f"{k}:{len(v)}" for k, v in buckets.items())
        print(f"collated {total} fragment(s) into [Unreleased] ({kinds})")
    elif args.cmd == "roll":
        text = CHANGELOG.read_text(encoding="utf-8")
        CHANGELOG.write_text(roll(text, args.version, args.date), encoding="utf-8")
        print(f"changelog: rolled Unreleased → [{args.version}] - {args.date}")
    elif args.cmd == "scaffold":
        added = scaffold(args.version)
        print(
            f"changelog: {'scaffolded draft' if added else 'already present'} v{args.version}"
            f" in {MARKETING_JSON.name} (polish the wording by hand)"
        )
    elif args.cmd == "notes":
        body = notes(args.version)
        if body:  # empty → print nothing so the caller's fallback chain kicks in
            print(body)
    elif args.cmd == "archive":
        n, path = archive(args.before, args.out, args.title)
        print(
            f"changelog: archived {n} release section(s) into {path.name}"
            if n
            else f"changelog: nothing dated before {args.before} to archive"
        )
    elif args.cmd == "lint-fragments":
        if args.paths:
            paths = [Path(p) for p in args.paths]
        elif FRAGMENTS_DIR.is_dir():
            paths = [
                p
                for p in sorted(FRAGMENTS_DIR.iterdir())
                if p.is_file() and p.name not in ("README.md", ".gitkeep")
            ]
        else:
            paths = []
        problems = lint_fragments(paths)
        if problems:
            raise SystemExit("unusable changelog fragment(s):\n  " + "\n  ".join(problems))
        print(f"changelog: {len(paths)} fragment(s) parse")
    elif args.cmd == "check":
        missing = missing_versions()
        if missing:
            raise SystemExit(
                f"changelog.json is missing entries for: {', '.join(missing)} "
                f"(run `scripts/changelog.py scaffold <version>` then polish)"
            )
        print("changelog: marketing changelog.json covers every released version")


if __name__ == "__main__":
    main()
