#!/usr/bin/env python3
"""Generate the **plugin API reference** pages from the source of truth — the code.

The plugin system is protoAgent's extension contract, and a contract you can't look up
isn't one. Every other plugin page is narrative (guides explain *how to build a thing*);
these pages are the lookup tier: every public symbol, its exact signature, and what the
code itself says about it. Hand-maintaining that is how docs rot — a new seam lands and
the reference silently stops being complete — so it is generated and CI-gated instead,
the same way ``scripts/gen_docs_nav.py`` + ``tests/test_docs_plugin.py`` keep the docs
plugin's nav honest.

    python scripts/gen_plugin_api.py            # write docs/reference/plugin-*.md
    python scripts/gen_plugin_api.py --check    # exit 1 if any committed page is stale

What it introspects, and what that pins:

* ``graph.plugins.manifest.PluginManifest`` → the ``protoagent.plugin.yaml`` schema. A new
  manifest field is undocumented for exactly as long as it takes CI to run.
* ``graph.plugins.registry.PluginRegistry`` → the ``register(registry)`` surface: every
  ``register_*`` seam plus the attributes a plugin reads (``config``, ``host``, …).
* ``graph.sdk`` → the consumption SDK (ADR 0043), grouped by the ``# ── section ──``
  banners the module already uses to organize itself.
* ``graph.plugins.host.PluginHost`` → the host services a surface/route may call.
* ``graph.plugins.testkit`` → the host-free test harness.
* ``graph.plugins.cli._build_parser`` → the ``python -m server plugin …`` subcommands,
  read straight off argparse so flags and defaults can't drift.

Prose comes from docstrings and, for dataclass fields, the comment block above the field —
both are already reference-grade here, and generating from them means a docstring edit *is*
a docs edit. ``ADR NNNN`` and ``#NNNN`` references are linkified on the way out (never
inside code spans, where they'd corrupt a code sample).
"""

from __future__ import annotations

import argparse
import ast
import inspect
import re
import sys
from dataclasses import MISSING, fields as dataclass_fields
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    # Import the host packages we introspect, however we were invoked. Guarded: under
    # pytest the repo root is already first on the path, and re-inserting it would
    # reorder imports for every test that runs after this module is loaded.
    sys.path.insert(0, str(REPO))

DOCS = REPO / "docs" / "reference"
GITHUB = "https://github.com/protoLabsAI/protoAgent"

BANNER = (
    "<!-- GENERATED by scripts/gen_plugin_api.py — DO NOT EDIT BY HAND.\n"
    "     Edit the docstrings/comments in the source module and re-run the generator:\n"
    "     `python scripts/gen_plugin_api.py` (CI runs it with --check). -->\n"
)


# ── linkifying + prose normalization ───────────────────────────────────────────────────


def _adr_map() -> dict[str, str]:
    """``"0018" → "/adr/0018-plugin-surfaces-routes-subagents"`` for every ADR on disk."""
    return {p.stem[:4]: f"/adr/{p.stem}" for p in sorted((REPO / "docs" / "adr").glob("[0-9][0-9][0-9][0-9]-*.md"))}


ADRS = _adr_map()

_ADR_RE = re.compile(r"\bADR (\d{4})\b")
_ISSUE_RE = re.compile(r"(?<![\w/#])#(\d{3,5})\b")
# Text shaped like an HTML tag — `<id>`, `<config_section>` — which Vue would try to parse.
_TAGLIKE_RE = re.compile(r"<(/?[A-Za-z_][^>\s]*)>")
# Split on code spans so we never linkify inside `like_this`.
_CODE_SPAN_RE = re.compile(r"(``[^`]+``|`[^`]+`)")


def _linkify(text: str) -> str:
    """Turn ``ADR 0018`` / ``#1642`` into links — outside code spans only."""

    def _one(chunk: str) -> str:
        # VitePress compiles markdown as Vue, so a bare `<id>` in prose is parsed as an
        # unclosed component and fails the docs build. Escape tag-shaped text (code spans,
        # which this function never sees, keep their angle brackets verbatim).
        chunk = _TAGLIKE_RE.sub(r"&lt;\1&gt;", chunk)
        chunk = _ADR_RE.sub(
            lambda m: f"[ADR {m.group(1)}]({ADRS[m.group(1)]})" if m.group(1) in ADRS else m.group(0), chunk
        )
        return _ISSUE_RE.sub(lambda m: f"[#{m.group(1)}]({GITHUB}/issues/{m.group(1)})", chunk)

    return "".join(part if _CODE_SPAN_RE.fullmatch(part) else _one(part) for part in _CODE_SPAN_RE.split(text))


_ARG_RE = re.compile(r"^(\s+)([*\w]+):\s*(.*)$")


def _render_arg_block(lines: list[str]) -> list[str]:
    """Turn a Google-style ``Args:`` body into a markdown list.

    Left as-is, the source's 4-space indentation makes markdown render the whole block as
    a code sample — monospace, with every `code span` inside it lost. A list keeps the
    parameter names scannable and the inline formatting intact.
    """
    out: list[str] = []
    for line in lines:
        m = _ARG_RE.match(line)
        if m and not line.startswith(" " * 8):
            out.append(f"- `{m.group(2)}` — {m.group(3).strip()}")
        elif out:  # continuation of the previous parameter
            out[-1] = f"{out[-1]} {line.strip()}"
        elif line.strip():
            out.append(line.strip())
    return out


def _clean_doc(doc: str | None) -> str:
    """Dedent a docstring and render it as markdown: RST roles and double backticks become
    code spans, Google-style ``Args:``/``Returns:`` sections become headed lists, and ADR
    and issue references become links."""
    if not doc:
        return "_No description yet — add a docstring in the source module._"
    # cleandoc, NOT textwrap.dedent: a docstring's first line carries no indentation, so
    # dedent finds a common prefix of "" and does nothing to the indented remainder. Python
    # 3.13 strips docstring indentation at compile time and 3.12 does not, so dedent made
    # the generated pages differ BY INTERPRETER — CI (3.12) could never agree with a 3.13
    # dev machine. cleandoc handles the first-line-unindented shape identically on both.
    text = inspect.cleandoc(doc)
    text = re.sub(r":(?:func|class|meth|mod|attr|data):`~?([^`]+)`", lambda m: f"`{m.group(1).split('.')[-1]}`", text)
    text = re.sub(r"``([^`]+)``", r"`\1`", text)

    lines: list[str] = []
    pending: list[str] = []  # body of the Args/Returns section currently being consumed

    def _flush() -> None:
        if pending:
            lines.extend(_render_arg_block(pending))
            lines.append("")
            pending.clear()

    in_section = False
    for line in text.split("\n"):
        if re.fullmatch(r"(Args|Arguments|Returns|Raises|Yields|Note|Example|Examples):", line.strip()):
            _flush()
            lines += [f"**{line.strip().rstrip(':')}:**", ""]
            in_section = True
            continue
        if in_section and (line.startswith("    ") or not line.strip()):
            if line.strip():
                pending.append(line)
            continue
        _flush()
        in_section = False
        lines.append(line)
    _flush()
    return _linkify("\n".join(lines))


def _prose(text: str) -> str:
    """Normalize a comment fragment into one markdown paragraph."""
    text = re.sub(r"``([^`]+)``", r"`\1`", text)
    return _linkify(re.sub(r"\s+", " ", text).strip())


_ABBREV = re.compile(r"\b(?:e\.g|i\.e|etc|vs|cf|approx|Dr|Mr|Ms)\.$")


def _first_sentence(text: str, limit: int = 200) -> str:
    """The first real sentence — abbreviation-aware, so ``(e.g. the delegate registry)``
    isn't truncated to ``e.g``. Falls back to a word-boundary trim past ``limit``."""
    flat = re.sub(r"\s+", " ", text).strip()
    if not flat:
        return ""
    out = ""
    for part in re.split(r"(?<=\.)\s+", flat):
        out = f"{out} {part}".strip() if out else part
        if not _ABBREV.search(out.rstrip()):
            break
    out = out.strip()
    if len(out) > limit:
        out = out[:limit].rsplit(" ", 1)[0].rstrip(",;:") + "…"
    return out.rstrip(".")


def _cell(text: str) -> str:
    """Make a fragment safe inside a markdown table cell."""
    return re.sub(r"\s+", " ", text).replace("|", "\\|").strip()


def _heading(text: str) -> str:
    """A section banner turned into a heading — capitalized, links left as plain text
    (a link inside a heading makes a mess of the generated anchor)."""
    text = text.strip()
    return text[:1].upper() + text[1:]


# ── reading documentation out of source ────────────────────────────────────────────────


def _comment_lines_above(source_lines: list[str], lineno: int) -> list[str]:
    """The contiguous ``#`` comment block directly above 1-indexed ``lineno``, raw.

    Dataclass fields and ``__init__`` attributes in this codebase carry their
    documentation as comments, not docstrings — that prose IS the reference text, so we
    read it rather than asking authors to duplicate it into a docstring.
    """
    out: list[str] = []
    i = lineno - 2  # 0-indexed line above the definition
    while i >= 0 and source_lines[i].strip().startswith("#"):
        out.append(re.sub(r"^\s*#\s?", "", source_lines[i]).rstrip())
        i -= 1
    return list(reversed(out))


# A comment block often documents a GROUP of fields, with one indented bullet per field:
#   config_section: the top-level YAML section the plugin claims (default: id)
#   config:    defaults for that section (key → default value)
# Parsing those bullets is what lets every field get its own row without asking anyone to
# restate documentation the source already carries.
_BULLET_RE = re.compile(r"^\s{2,}([a-z_]+(?:/[a-z_]+)*):\s+(.*)$")


def _parse_comment_block(lines: list[str]) -> tuple[str, dict[str, str]]:
    """Split a comment block into ``(intro prose, {field name: its bullet text})``."""
    intro: list[str] = []
    bullets: dict[str, list[str]] = {}
    current: str | None = None
    for line in lines:
        m = _BULLET_RE.match(line)
        if m:
            current = m.group(1)
            for name in current.split("/"):
                bullets[name] = [m.group(2)]
            continue
        if current and line.startswith("    "):  # continuation of the current bullet
            for name in current.split("/"):
                bullets[name].append(line.strip())
            continue
        current = None
        intro.append(line.strip())
    return " ".join(x for x in intro if x).strip(), {k: " ".join(v).strip() for k, v in bullets.items()}


def _field_docs(cls: type) -> dict[str, str]:
    """Documentation for every field of a dataclass.

    A field uses (1) the bullet naming it in the nearest comment block at or above it,
    else (2) its own block's intro prose. A field that resolves to nothing is a gap in the
    source, and the page says so out loud rather than rendering an empty cell.
    """
    src = inspect.getsource(inspect.getmodule(cls))
    lines = src.split("\n")
    tree = ast.parse(src)
    docs: dict[str, str] = {}
    bullets_seen: dict[str, str] = {}
    for node in ast.walk(tree):
        if not (isinstance(node, ast.ClassDef) and node.name == cls.__name__):
            continue
        for stmt in node.body:
            if not (isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)):
                continue
            name = stmt.target.id
            block = _comment_lines_above(lines, stmt.lineno)
            if block:
                intro, bullets = _parse_comment_block(block)
                bullets_seen.update(bullets)
                docs[name] = _prose(bullets.get(name) or intro)
            else:
                docs[name] = _prose(bullets_seen.get(name, ""))
    return docs


def _init_attr_docs(cls: type) -> dict[str, str]:
    """``self.<attr> → its documentation`` from the comments inside ``__init__``."""
    src = inspect.getsource(inspect.getmodule(cls))
    lines = src.split("\n")
    tree = ast.parse(src)
    out: dict[str, str] = {}
    for node in ast.walk(tree):
        if not (isinstance(node, ast.ClassDef) and node.name == cls.__name__):
            continue
        for stmt in node.body:
            if not (isinstance(stmt, ast.FunctionDef) and stmt.name == "__init__"):
                continue
            for inner in stmt.body:
                target = None
                if isinstance(inner, ast.AnnAssign):
                    target = inner.target
                elif isinstance(inner, ast.Assign) and len(inner.targets) == 1:
                    target = inner.targets[0]
                if (
                    isinstance(target, ast.Attribute)
                    and isinstance(target.value, ast.Name)
                    and target.value.id == "self"
                ):
                    out[target.attr] = _prose(" ".join(_comment_lines_above(lines, inner.lineno)))
    return out


def _sig(fn: Any, *, drop_self: bool = False) -> str:
    """A rendered signature, minus ``self``. Annotations are kept — they're the contract."""
    sig = inspect.signature(fn)
    params = list(sig.parameters.values())
    if drop_self and params and params[0].name == "self":
        params = params[1:]
    rendered = str(sig.replace(parameters=params))
    # `from __future__ import annotations` makes every annotation a string literal;
    # rendering those quotes would put `-> 'Any'` in the docs. Strip them.
    return re.sub(r"'([^']*)'", r"\1", rendered)


def _public_functions(module: Any) -> list[tuple[str, Any]]:
    """Public callables *defined in* ``module`` — never re-exports, which are documented
    where they live; listing them here would claim ownership the module doesn't have."""
    return [
        (name, obj)
        for name, obj in vars(module).items()
        if not name.startswith("_")
        and (inspect.isfunction(obj) or inspect.iscoroutinefunction(obj))
        and getattr(obj, "__module__", None) == module.__name__
    ]


def _public_methods(cls: type) -> list[tuple[str, Any]]:
    return [
        (n, f)
        for n, f in sorted(vars(cls).items())
        if not n.startswith("_") and (inspect.isfunction(f) or inspect.iscoroutinefunction(f))
    ]


def _section_banners(module: Any) -> dict[int, str]:
    """``# ── Title ── `` banner comments → ``{line number: title}``.

    ``graph/sdk.py`` already groups itself with these; reusing them means the reference's
    contents page is the module's own organization, not a second one to keep in sync.
    """
    out: dict[int, str] = {}
    for i, line in enumerate(inspect.getsource(module).split("\n"), start=1):
        m = re.match(r"^# ─+\s*(.+?)\s*─+\s*$", line)
        if m:
            out[i] = m.group(1).strip()
    return out


# ── page builders ──────────────────────────────────────────────────────────────────────

UNDOCUMENTED = "_Undocumented — document it in the source and re-run the generator._"


def _fmt_default(f: Any) -> str:
    if f.default is not MISSING:
        return f"`{f.default!r}`"
    if f.default_factory is not MISSING:  # type: ignore[misc]
        try:
            return f"`{f.default_factory()!r}`"  # type: ignore[misc]
        except Exception:  # noqa: BLE001 — a factory we can't call is still documentable
            return "_(factory)_"
    return "**required**"


def _fmt_type(f: Any) -> str:
    t = f.type if isinstance(f.type, str) else getattr(f.type, "__name__", str(f.type))
    return f"`{t}`"


def page_manifest() -> str:
    from graph.plugins.manifest import MANIFEST_FILENAME, PluginManifest

    docs = _field_docs(PluginManifest)
    skip = {"path"}  # resolved by the loader, never authored in YAML
    fields = [f for f in dataclass_fields(PluginManifest) if f.name not in skip]
    out = [
        BANNER,
        "# Plugin manifest",
        "",
        f"Every field of `{MANIFEST_FILENAME}` — the file that makes a directory a plugin.",
        "Generated from the `PluginManifest` dataclass in `graph/plugins/manifest.py`, which is",
        "what the loader actually reads, so this list is complete by construction.",
        "",
        "The manifest is **declarative on purpose**: it is parsed before the plugin's Python is",
        "ever imported, so the host can gate, configure, and display a plugin it has never run.",
        "That is what makes an install reviewable and a disabled plugin inert.",
        "",
        "See [Plugins](/guides/plugins) for how to use these fields, and",
        "[Install & publish plugins](/guides/plugin-registry) for the distribution ones.",
        "",
        "## At a glance",
        "",
        "| Field | Type | Default | Meaning |",
        "|---|---|---|---|",
    ]
    for f in fields:
        out.append(
            f"| [`{f.name}`](#field-{f.name.replace('_', '-')}) | {_fmt_type(f)} | {_fmt_default(f)} | {_cell(_first_sentence(docs.get(f.name, '')))} |"
        )
    out += ["", "## Fields", ""]
    for f in fields:
        out += [
            f"### `{f.name}` {{#field-{f.name.replace('_', '-')}}}",
            "",
            f"- **Type** {_fmt_type(f)} · **Default** {_fmt_default(f)}",
            "",
            docs.get(f.name) or UNDOCUMENTED,
            "",
        ]
    return "\n".join(out).rstrip() + "\n"


def page_registry() -> str:
    from graph.plugins.host import PluginHost
    from graph.plugins.registry import PluginRegistry

    attr_docs = _init_attr_docs(PluginRegistry)
    methods = _public_methods(PluginRegistry)
    out = [
        BANNER,
        "# Plugin registry API",
        "",
        "The object your plugin's `register(registry)` receives — the whole Python extension",
        "surface in one place. Generated from `graph/plugins/registry.py`.",
        "",
        "```python",
        "def register(registry):",
        '    """Called once at plugin load, before the graph is built."""',
        "    registry.register_tool(my_tool)",
        "```",
        "",
        "Two properties of this surface are worth knowing before you use any of it:",
        "",
        "**Every seam is best-effort.** A `register_*` call with bad arguments logs a warning and",
        "returns — it never raises into the loader, because one malformed plugin must not stop an",
        "agent from booting. If a seam seems to have done nothing, read the log.",
        "",
        "**Guard for older hosts.** A plugin that must run against a host predating a seam should",
        '`hasattr(registry, "register_x")` before calling it. That is also why',
        "[`FakeRegistry`](/reference/plugin-testkit) mirrors this class method-for-method, with a",
        "test that fails CI when it stops matching.",
        "",
        "## Attributes",
        "",
        "Read these in `register()` and close over them for your tools, routes, and surfaces.",
        "",
    ]
    for name in ["plugin_id", "plugin_dir", "config", "config_section", "host"]:
        out += [f"### `registry.{name}`", "", attr_docs.get(name) or UNDOCUMENTED, ""]
    out += ["## Methods", "", "| Method | Purpose |", "|---|---|"]
    for name, fn in methods:
        summary = _cell(_first_sentence(_clean_doc(fn.__doc__)))
        out.append(f"| [`{name}()`](#registry-{name.replace('_', '-')}) | {summary} |")
    out.append("")
    for name, fn in methods:
        out += [
            f"### `registry.{name}` {{#registry-{name.replace('_', '-')}}}",
            "",
            "```python",
            f"registry.{name}{_sig(fn, drop_self=True)}",
            "```",
            "",
            _clean_doc(fn.__doc__),
            "",
        ]
    out += [
        "## Host services — `registry.host`",
        "",
        "Services the *server* owns: calling the agent, the event bus, live config. The server",
        "populates them before any surface starts, so they are `None` at import time and in",
        "host-free tests — **always guard**. Generated from `graph/plugins/host.py`.",
        "",
        "| Service | Type | Purpose |",
        "|---|---|---|",
    ]
    host_docs = _field_docs(PluginHost)
    for f in dataclass_fields(PluginHost):
        t = (f.type if isinstance(f.type, str) else str(f.type)).replace("Optional[", "").rstrip("]")
        out.append(f"| `host.{f.name}` | `{t}` | {_cell(host_docs.get(f.name, ''))} |")
    return "\n".join(out).rstrip() + "\n"


def page_sdk() -> str:
    from graph import sdk

    banners = _section_banners(sdk)
    placed: list[tuple[str, str, Any]] = []
    for name, fn in _public_functions(sdk):
        line = fn.__code__.co_firstlineno
        section = ""
        for bline, title in sorted(banners.items()):
            if bline < line:
                section = title
            else:
                break
        placed.append((section or "Core", name, fn))
    order: list[str] = []
    for section, _, _ in placed:
        if section not in order:
            order.append(section)

    out = [
        BANNER,
        "# Plugin SDK — `graph.sdk`",
        "",
        "The consumption SDK ([ADR 0043](/adr/0043-plugin-consumption-sdk-workflows-extraction)):",
        "a **stable, importable** surface onto agent capability, so a plugin can run a subagent,",
        "search knowledge, schedule work, or record a metric without reaching into core internals.",
        "The distinction matters — internals are free to change underneath you between releases;",
        "this module and [`registry.host`](/reference/plugin-registry-api#host-services-registry-host)",
        "are the two surfaces that aren't.",
        "",
        "```python",
        "from graph import sdk",
        "",
        "answer = await sdk.complete('Summarize the changelog')",
        "```",
        "",
        "Import it lazily (inside the function that uses it) if your plugin must also run",
        "host-free in its own test suite. Generated from `graph/sdk.py`; the sections below are",
        "the module's own.",
        "",
        "## Contents",
        "",
    ]
    for section in order:
        names = sorted(n for s, n, _ in placed if s == section)
        links = ", ".join(f"[`{n}()`](#sdk-{n.replace('_', '-')})" for n in names)
        out += [f"**{_heading(section)}** — {links}", ""]
    for section in order:
        out += [f"## {_heading(section)}", ""]
        for s, name, fn in placed:
            if s != section:
                continue
            prefix = "await " if inspect.iscoroutinefunction(fn) else ""
            out += [
                f"### `sdk.{name}` {{#sdk-{name.replace('_', '-')}}}",
                "",
                "```python",
                f"{prefix}sdk.{name}{_sig(fn)}",
                "```",
                "",
                _clean_doc(fn.__doc__),
                "",
            ]
    return "\n".join(out).rstrip() + "\n"


def page_testkit() -> str:
    from graph.plugins import testkit

    out = [
        BANNER,
        "# Plugin testkit",
        "",
        "`graph/plugins/testkit.py` — a **host-free** harness that loads a plugin exactly the way",
        "the runtime does (same synthetic package name, so relative imports and module-level",
        "`@tool` decorators work) while stubbing the parts of protoAgent that aren't installed.",
        "",
        "That combination is the point: a standalone plugin repo can exercise its real modules in",
        "CI with no protoAgent present. `python -m server plugin new --tests` vendors this file",
        "into a new plugin as `tests/_plugin_testkit.py`; bundled plugins import it directly.",
        "",
        "```python",
        "from graph.plugins.testkit import FakeRegistry, load_plugin",
        "",
        "def test_register_binds_tools():",
        "    pkg = load_plugin(PLUGIN_DIR, 'my-plugin')",
        "    reg = FakeRegistry(plugin_id='my-plugin')",
        "    pkg.register(reg)",
        "    assert [t.name for t in reg.tools] == ['my_tool']",
        "```",
        "",
        "## Functions",
        "",
    ]
    for name, fn in sorted(_public_functions(testkit)):
        out += [f"### `{name}`", "", "```python", f"{name}{_sig(fn)}", "```", "", _clean_doc(fn.__doc__), ""]
    out += [
        "## `FakeRegistry`",
        "",
        _clean_doc(testkit.FakeRegistry.__doc__),
        "",
        "It mirrors every public method of [`PluginRegistry`](/reference/plugin-registry-api)",
        "**with identical signatures** — `tests/test_plugin_testkit.py` asserts that by",
        "introspection, so a new registry seam fails CI until the harness can exercise it. Calls",
        "land on attributes named after the seam (`reg.tools`, `reg.routers`, `reg.surfaces`, …)",
        "for your assertions.",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def page_cli() -> str:
    from graph.plugins.cli import _build_parser

    parser = _build_parser()
    subparsers: dict[str, argparse.ArgumentParser] = {}
    helps: dict[str, str] = {}
    for action in parser._actions:  # noqa: SLF001 — argparse exposes no public walk
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            subparsers = dict(action.choices)
            helps = {c.dest: (c.help or "") for c in action._get_subactions()}  # noqa: SLF001
            break

    out = [
        BANNER,
        "# Plugin CLI",
        "",
        "`python -m server plugin …` — scaffold, install, and manage plugins from a shell.",
        "Generated from the argparse definition in `graph/plugins/cli.py`.",
        "",
        "Two deliberate non-behaviors, because both are consent boundaries",
        "([ADR 0027](/adr/0027-install-plugins-from-git-url)): **install does not enable** a",
        "plugin, and **install does not install its Python dependencies**. Fetching code is not",
        "running it, so each step is a separate, explicit act.",
        "",
        "| Command | Purpose |",
        "|---|---|",
    ]
    for name in subparsers:
        out.append(f"| [`{name}`](#cmd-{name}) | {_cell(helps.get(name, ''))} |")
    out.append("")
    for name, sub in subparsers.items():
        usage = " ".join(sub.format_usage().replace("usage: ", "").split())
        out += [f"## `{name}` {{#cmd-{name}}}", "", "```", usage, "```", ""]
        if helps.get(name):
            out += [helps[name][0].upper() + helps[name][1:] + ".", ""]
        rows = []
        for a in sub._actions:  # noqa: SLF001
            if a.dest == "help":
                continue
            flags = ", ".join(f"`{o}`" for o in a.option_strings) or f"`{a.dest}`"
            default = "" if a.default in (None, False) else f" (default `{a.default!r}`)"
            rows.append(f"| {flags} | {_cell((a.help or '') + default)} |")
        if rows:
            out += ["| Argument | Meaning |", "|---|---|", *rows, ""]
    return "\n".join(out).rstrip() + "\n"


PAGES = {
    "plugin-manifest.md": page_manifest,
    "plugin-registry-api.md": page_registry,
    "plugin-sdk-api.md": page_sdk,
    "plugin-testkit.md": page_testkit,
    "plugin-cli.md": page_cli,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if any committed page is stale")
    args = ap.parse_args()

    stale = []
    for filename, builder in PAGES.items():
        target = DOCS / filename
        content = builder()
        if args.check:
            if (target.read_text(encoding="utf-8") if target.exists() else "") != content:
                stale.append(filename)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            print(f"wrote {target.relative_to(REPO)}")

    if args.check and stale:
        print("Stale generated plugin reference pages: " + ", ".join(stale), file=sys.stderr)
        print("Run `python scripts/gen_plugin_api.py` and commit the result.", file=sys.stderr)
        return 1
    if args.check:
        print("plugin API reference is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
