#!/usr/bin/env bash
#
# One-command fleet-tracing setup for ANY rig (the flywheel Observe, #1897).
#
# Two independent parts, both handled here:
#   1. ENABLE the exporter for this rig's launch method (optional --enable).
#   2. SHIP this rig's raw trace dumps to the lab box (`ava`) over the tailnet,
#      on a daily schedule — ava's cron then redacts + forwards to the dataset.
#
# Raw dumps only ever travel between YOUR machines over encrypted tailscale; the
# redaction boundary (regex + openai/privacy-filter) stays on ava, before the
# shared corpus. So a laptop/desktop needs NO model or venv — it just ships raw.
#
# Usage:
#   scripts/setup_fleet_tracing.sh [--enable] [--rig-name NAME] [--ava-host HOST]
#                                  [--time HH:MM] [--now]
#
#   --enable      also turn the exporter on for this rig's launch method
#                 (systemd EnvironmentFile / shell profile hint). For the
#                 DESKTOP APP, don't use this — flip "Fleet trace export" in
#                 Settings ▸ Telemetry instead (no env hackery on a GUI app).
#   --rig-name    label for this rig on ava (default: hostname short name)
#   --ava-host    tailnet host for the lab box (default: ava)
#   --time        daily ship time, 24h (default: 03:35, after ava's 03:15 redact
#                 so today's ships tomorrow; pick earlier to lead ava's run)
#   --now         run one ship immediately after install (smoke test)
set -euo pipefail

RIG_NAME=""; AVA_HOST="ava"; ENABLE=0; SHIP_TIME="03:35"; RUN_NOW=0
while [ $# -gt 0 ]; do
  case "$1" in
    --enable) ENABLE=1;;
    --rig-name) RIG_NAME="$2"; shift;;
    --ava-host) AVA_HOST="$2"; shift;;
    --time) SHIP_TIME="$2"; shift;;
    --now) RUN_NOW=1;;
    -h|--help) sed -n '2,40p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
  shift
done

BOX_ROOT="${PROTOAGENT_HOME:-$HOME/.protoagent}"
RIG_NAME="${RIG_NAME:-$(hostname -s 2>/dev/null || hostname)}"
# Filesystem/label-safe rig name.
RIG_NAME="$(printf '%s' "$RIG_NAME" | tr -c 'A-Za-z0-9._-' '-')"
OS="$(uname -s)"

echo "▶ fleet-tracing setup"
echo "  rig      : $RIG_NAME"
echo "  ava host : $AVA_HOST"
echo "  local src: $BOX_ROOT/*/fleet-traces"
echo "  ship at  : $SHIP_TIME daily"

# The ship command: rsync each local instance's dumps to ava under a rig-scoped
# instance name so ava's cron picks them up (globs ~/.protoagent/*/fleet-traces)
# and labels them "<rig>-<instance>__". A generated helper so both the schedule
# and --now call exactly the same thing.
SHIP_SH="$BOX_ROOT/ship-fleet-traces.sh"
mkdir -p "$BOX_ROOT"
cat > "$SHIP_SH" <<SHIP
#!/usr/bin/env bash
# Auto-generated by setup_fleet_tracing.sh — ships this rig's raw trace dumps to
# the lab box over tailnet. ava's daily cron redacts + forwards to the dataset.
set -euo pipefail
BOX_ROOT="\${PROTOAGENT_HOME:-\$HOME/.protoagent}"
for src in "\$BOX_ROOT"/*/fleet-traces; do
  [ -d "\$src" ] || continue
  inst="\$(basename "\$(dirname "\$src")")"
  rsync -az --include='fleet-traces-*.jsonl' --include='*/' --exclude='*' \\
    "\$src"/ "$AVA_HOST:.protoagent/$RIG_NAME-\$inst/fleet-traces/" \\
    && echo "\$(date -Iseconds) shipped \$inst -> $AVA_HOST ($RIG_NAME-\$inst)"
done
SHIP
chmod +x "$SHIP_SH"
echo "  wrote ship helper: $SHIP_SH"

# ── Schedule the daily ship (launchd on macOS, cron elsewhere) ────────────────
HH="${SHIP_TIME%%:*}"; MM="${SHIP_TIME##*:}"
if [ "$OS" = "Darwin" ]; then
  LABEL="ai.protolabs.fleet-traces-ship"
  PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$SHIP_SH</string></array>
  <key>StartCalendarInterval</key><dict><key>Hour</key><integer>$((10#$HH))</integer><key>Minute</key><integer>$((10#$MM))</integer></dict>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/fleet-traces-ship.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/fleet-traces-ship.log</string>
  <key>RunAtLoad</key><false/>
</dict></plist>
PLIST
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load "$PLIST"
  echo "  scheduled: launchd $LABEL ($PLIST)"
else
  LINE="$((10#$MM)) $((10#$HH)) * * * $SHIP_SH >> /tmp/fleet-traces-ship.log 2>&1"
  TMP="$(mktemp)"; crontab -l 2>/dev/null > "$TMP" || true
  grep -v "ship-fleet-traces.sh" "$TMP" > "$TMP.n" || true; mv "$TMP.n" "$TMP"
  printf '\n# Fleet-tracing: ship raw dumps to %s daily (#1897)\n%s\n' "$AVA_HOST" "$LINE" >> "$TMP"
  crontab "$TMP"; rm -f "$TMP"
  echo "  scheduled: cron @ $SHIP_TIME"
fi

# ── Optionally enable the exporter for this rig's launch method ───────────────
if [ "$ENABLE" = 1 ]; then
  if [ "$OS" = "Linux" ] && [ -f "$HOME/.config/systemd/user/protoagent.service" ]; then
    ENVF="$BOX_ROOT/protoagent.env"; touch "$ENVF"
    grep -q '^PROTOAGENT_FLEET_TRACE_EXPORT=' "$ENVF" || echo 'PROTOAGENT_FLEET_TRACE_EXPORT=1' >> "$ENVF"
    echo "  enabled: added PROTOAGENT_FLEET_TRACE_EXPORT=1 to $ENVF"
    echo "           → run: systemctl --user restart protoagent"
  else
    echo "  enable: add this to the shell/profile that launches the agent:"
    echo "           export PROTOAGENT_FLEET_TRACE_EXPORT=1"
    echo "          (desktop app: flip Settings ▸ Telemetry ▸ Fleet trace export instead)"
  fi
fi

if [ "$RUN_NOW" = 1 ]; then
  echo "▶ shipping now (smoke test)…"; bash "$SHIP_SH" || echo "  (nothing to ship yet — no dumps present)"
fi

echo "✓ done. Ensure 'ssh $AVA_HOST' works over the tailnet (key auth)."
