#!/usr/bin/env python3
"""Freeze the headless protoAgent server into a single-file Tauri sidecar.

Produces ``apps/desktop/src-tauri/binaries/protoagent-server-<target-triple>``
— the ``externalBin`` Tauri bundles and launches. The desktop app renders the
React console itself, so the binary stays as small as this dependency stack allows.

Run from a venv with the runtime deps + PyInstaller installed:

    pip install -r requirements.txt pyinstaller "mcp[cli]"
    python apps/desktop/sidecar/build_sidecar.py

(``mcp[cli]`` is a build-env-only need: ``--collect-all mcp`` imports every mcp
submodule, and ``mcp.cli`` raises at import when typer is missing.)

The target triple matches Tauri's expectation (``rustc`` host), so the binary
lands at the exact name Tauri looks for during ``tauri build``.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
BINARIES_DIR = REPO / "apps" / "desktop" / "src-tauri" / "binaries"
NAME = "protoagent-server"

# Read-only defaults the frozen server reads via REPO_ROOT/config (which
# resolves to _MEIPASS/config inside the bundle). Live state (langgraph-config
# .yaml, secrets.yaml, .setup-complete) is NOT bundled — it's written at
# runtime to PROTOAGENT_CONFIG_DIR. Never bundle secrets.yaml or the live YAML.
BUNDLED_DATA: list[tuple[str, str]] = [
    # Version truth (version-coherence Cross-cutting B, docs/dev/version-coherence.md):
    # `paths.package_version()` has no installed-package metadata in a frozen binary,
    # so it falls back to reading `pyproject.toml` at _MEIPASS. Bundle it (top level)
    # so the desktop app reports its REAL version instead of "0.0.0" — which otherwise
    # blinds the A2A card, the fleet version handshake, runtime status, and the plugin
    # `min_protoagent_version` compat gate (every plugin with one is wrongly refused).
    ("pyproject.toml", "."),
    ("config/langgraph-config.example.yaml", "config"),
    ("config/SOUL.md", "config"),
    # The curated Discover directory (ADR 0059). The catalog route reads it from
    # REPO_ROOT/config (→ _MEIPASS/config when frozen); without it the desktop app's
    # Plugins ▸ Discover shows "0 official plugins" (every entry is unreachable).
    ("config/plugin-catalog.json", "config"),
    ("config/soul-presets", "config/soul-presets"),
    # The bundled first-party skills (config/skills/*/SKILL.md — release-notes,
    # web-research). `_build_skills_index` (server/agent_init.py) seeds the skill
    # index from REPO_ROOT/config/skills (→ _MEIPASS/config/skills when frozen),
    # exactly like SOUL.md/soul-presets above. Without this entry the directory
    # never lands in the bundle, so the frozen desktop app indexes 0 SKILL.md
    # skills — the `/skill` library is silently empty.
    ("config/skills", "config/skills"),
    ("static", "static"),
    # The DS plugin-kit (/_ds/plugin-kit.{css,js}) — the theme kit every plugin iframe
    # loads to match the console (operator_api/web.py serves it from
    # apps/web/dist/_ds). The web build emits it there, but the desktop build freezes
    # this sidecar BEFORE the web build, so stage it from public/_ds into the dist path
    # the server reads (→ _MEIPASS/apps/web/dist/_ds when frozen). Without it, plugin
    # views (Notes, …) render with no design system — their /_ds/plugin-kit.* 404s.
    # (Generated by the "stage the DS plugin-kit" CI step before this runs.)
    ("apps/web/public/_ds", "apps/web/dist/_ds"),
    # Bundled first-party plugins (ADR 0018/0019). Loaded by file path (importlib)
    # at runtime, so PyInstaller's import-scan misses them; ship the tree as data so
    # the frozen app finds them under _MEIPASS/plugins (the loader's bundle root).
    # Externals (Discord, Google, …) install at runtime into the live dir (ADR 0058).
    ("plugins", "plugins"),
    # The published docs corpus — the `docs` plugin reads it (`docs/` beside the bundled
    # `plugins/` under _MEIPASS) to power docs_search/docs_read + the Docs view. Only the
    # Diátaxis sections + ADRs; `docs/dev` (internal) and `.vitepress` (build) are excluded.
    ("docs/tutorials", "docs/tutorials"),
    ("docs/guides", "docs/guides"),
    ("docs/reference", "docs/reference"),
    ("docs/explanation", "docs/explanation"),
    ("docs/adr", "docs/adr"),
]

# Packages PyInstaller's static analysis under-collects (dynamic imports +
# importlib.metadata entry points). --collect-all pulls modules + data + metadata.
COLLECT_ALL = [
    "langchain",
    "langchain_core",
    "langchain_openai",
    "langgraph",
    "ddgs",
    "langfuse",
    "croniter",
    # A2A 1.0 (ADR 0014): the SDK + the protoLabs conventions layer (git-dep).
    # Both pull submodules/metadata that a bare import-scan misses — without a
    # full collect, the frozen `protolabs_a2a` is missing `build_agent_card`.
    "a2a",
    "protolabs_a2a",
    # a2a-sdk[sqlite] durable task/push stores: imported lazily by the SDK, so
    # the import-scan misses them — collect explicitly.
    "aiosqlite",
    "sqlalchemy",
    # Comms-plugin runtime deps (ADR 0058): a plugin installed at runtime in the
    # frozen app can only import what's bundled. `websockets` is what the Discord /
    # Slack comms plugins use (httpx is already pulled by the core deps); `tools` is
    # the core tools package, collected whole because a plugin may import a core tool
    # module by file path (the import-scan misses those).
    "websockets",
    "tools",
    # MCP client (tools/mcp_tools) — connect external MCP servers; the SDK is lazily
    # imported, so collect it explicitly. (An external Google Gmail/Calendar MCP
    # plugin re-invokes the frozen binary via the generic ``--mcp-plugin <id>`` shim.)
    "mcp",
    # Markdown renderer for the bundled `docs` plugin's reader view — imported only by
    # the path-loaded plugin, so the import-scan misses it; collect explicitly.
    "markdown_it",
]

# Google client libraries (ADR 0017) — bundled only when installed in the build
# env (``requirements-google.txt``). Keeps a lean build (no google) working;
# install the extra to ship Gmail/Calendar in the frozen app.
OPTIONAL_COLLECT_ALL = [
    "google.auth",
    "google.oauth2",
    "google_auth_oauthlib",
    "googleapiclient",
]

# tkinter is GUI dead weight in a headless server and a freeze hazard — exclude it.
# (Gradio + the chat_ui module it backed were removed from the project entirely.)
EXCLUDE = ["tkinter"]


def target_triple() -> str:
    """Tauri names sidecars ``<bin>-<rustc-host-triple>``; match it."""
    out = subprocess.run(["rustc", "-Vv"], capture_output=True, text=True, check=True).stdout
    for line in out.splitlines():
        if line.startswith("host:"):
            return line.split(":", 1)[1].strip()
    raise SystemExit("could not determine rustc host triple (is rustc installed?)")


def main() -> None:
    triple = target_triple()
    work = REPO / "build" / "sidecar"
    sep = ";" if os.name == "nt" else ":"

    add_data: list[str] = []
    for src, dest in BUNDLED_DATA:
        if (REPO / src).exists():
            add_data += ["--add-data", f"{REPO / src}{sep}{dest}"]
        else:
            print(f"warning: bundled data missing, skipping: {src}", file=sys.stderr)

    collect: list[str] = []
    for pkg in COLLECT_ALL:
        collect += ["--collect-all", pkg]
    # Optional Google libs: collect only what's importable in this build env.
    import importlib.util

    for pkg in OPTIONAL_COLLECT_ALL:
        if importlib.util.find_spec(pkg) is not None:
            collect += ["--collect-all", pkg]
        else:
            print(f"note: optional package not installed, skipping: {pkg} "
                  "(install requirements-google.txt to ship Gmail/Calendar)",
                  file=sys.stderr)
    exclude: list[str] = []
    for mod in EXCLUDE:
        exclude += ["--exclude-module", mod]

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile", "--noconfirm", "--clean",
        "--name", NAME,
        "--distpath", str(work / "dist"),
        "--workpath", str(work / "build"),
        "--specpath", str(work),
        *exclude, *add_data, *collect,
        # ADR 0023: server.py is now the `server` package; freeze its module
        # entry point. PyInstaller bundles the whole `server` package and the
        # `--add-data` assets land at _MEIPASS top level (server/_bundle_root
        # resolves there when frozen).
        str(REPO / "server" / "__main__.py"),
    ]
    print("running:", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=str(REPO))

    BINARIES_DIR.mkdir(parents=True, exist_ok=True)
    suffix = ".exe" if os.name == "nt" else ""
    built = work / "dist" / f"{NAME}{suffix}"
    dest = BINARIES_DIR / f"{NAME}-{triple}{suffix}"
    shutil.copy2(built, dest)
    os.chmod(dest, 0o755)
    print(f"\nsidecar -> {dest}")


if __name__ == "__main__":
    main()
