#!/usr/bin/env python3
"""Freeze the headless protoAgent server into a single-file Tauri sidecar.

Produces ``apps/desktop/src-tauri/binaries/protoagent-server-<target-triple>``
— the ``externalBin`` Tauri bundles and launches. The desktop app renders the
React console itself, so the binary stays as small as this dependency stack allows.

Run from a venv with the runtime deps + PyInstaller installed:

    pip install -r requirements.txt pyinstaller "mcp[cli]"
    python apps/desktop/sidecar/build_sidecar.py

(``mcp[cli]`` is a build-env-only need: ``--collect-all mcp`` imports every mcp
submodule, and ``mcp.cli`` raises at import when typer is missing.)

The target triple matches Tauri's expectation (``rustc`` host), so the binary
lands at the exact name Tauri looks for during ``tauri build``.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
BINARIES_DIR = REPO / "apps" / "desktop" / "src-tauri" / "binaries"
NAME = "protoagent-server"

# Read-only defaults the frozen server reads via REPO_ROOT/config (which
# resolves to _MEIPASS/config inside the bundle). Live state (langgraph-config
# .yaml, secrets.yaml, .setup-complete) is NOT bundled — it's written at
# runtime to PROTOAGENT_CONFIG_DIR. Never bundle secrets.yaml or the live YAML.
BUNDLED_DATA: list[tuple[str, str]] = [
    # Version truth (version-coherence Cross-cutting B, docs/dev/version-coherence.md):
    # `paths.package_version()` has no installed-package metadata in a frozen binary,
    # so it falls back to reading `pyproject.toml` at _MEIPASS. Bundle it (top level)
    # so the desktop app reports its REAL version instead of "0.0.0" — which otherwise
    # blinds the A2A card, the fleet version handshake, runtime status, and the plugin
    # `min_protoagent_version` compat gate (every plugin with one is wrongly refused).
    ("pyproject.toml", "."),
    ("config/langgraph-config.example.yaml", "config"),
    ("config/SOUL.md", "config"),
    # The curated Discover directory (ADR 0059). The catalog route reads it from
    # REPO_ROOT/config (→ _MEIPASS/config when frozen); without it the desktop app's
    # Plugins ▸ Discover shows "0 official plugins" (every entry is unreachable).
    ("config/plugin-catalog.json", "config"),
    # The curated common-MCP-server picker (Settings ▸ MCP ▸ Browse common servers).
    # `/api/mcp/catalog` reads it from REPO_ROOT/config (→ _MEIPASS/config when frozen);
    # without it the desktop app shows "no servers match" (same trap as the plugin
    # catalog above).
    ("config/mcp-catalog.json", "config"),
    # The new-agent archetype directory (ADR 0042/0083). `_load_archetype_catalog`
    # (operator_api/fleet_routes.py) reads it from REPO_ROOT/config (→ _MEIPASS/config
    # when frozen) and falls back to Basic + Custom when it's absent — so without this
    # entry the desktop app's new-agent picker silently loses every catalog archetype
    # (Cowork), and nothing errors. Same trap as the plugin/MCP catalogs above.
    ("config/archetype-catalog.json", "config"),
    ("config/soul-presets", "config/soul-presets"),
    # The document-baseline pin list (ADR 0092 / ADR 0094). runtime/python_install.py
    # reads it (→ _MEIPASS/sidecar/requirements-docs.txt when frozen) to pip the doc
    # libs into the managed CPython the execute_code child spawns — the copies
    # DOC_COLLECT_ALL bundles into the PYZ are host-process-only and unreachable from
    # any external interpreter, so without this entry the provisioned runtime would
    # have an interpreter but no python-docx/openpyxl/pptx/reportlab to import.
    ("apps/desktop/sidecar/requirements-docs.txt", "sidecar"),
    # The bundled first-party skills (config/skills/*/SKILL.md — release-notes,
    # web-research). `_build_skills_index` (server/agent_init.py) seeds the skill
    # index from REPO_ROOT/config/skills (→ _MEIPASS/config/skills when frozen),
    # exactly like SOUL.md/soul-presets above. Without this entry the directory
    # never lands in the bundle, so the frozen desktop app indexes 0 SKILL.md
    # skills — the `/skill` library is silently empty.
    ("config/skills", "config/skills"),
    ("static", "static"),
    # The DS plugin-kit (/_ds/plugin-kit.{css,js}) — the theme kit every plugin iframe
    # loads to match the console (operator_api/web.py serves it from
    # apps/web/dist/_ds). The web build emits it there, but the desktop build freezes
    # this sidecar BEFORE the web build, so stage it from public/_ds into the dist path
    # the server reads (→ _MEIPASS/apps/web/dist/_ds when frozen). Without it, plugin
    # views (Notes, …) render with no design system — their /_ds/plugin-kit.* 404s.
    # (Generated by the "stage the DS plugin-kit" CI step before this runs.)
    ("apps/web/public/_ds", "apps/web/dist/_ds"),
    # Bundled first-party plugins (ADR 0018/0019). Loaded by file path (importlib)
    # at runtime, so PyInstaller's import-scan misses them; ship the tree as data so
    # the frozen app finds them under _MEIPASS/plugins (the loader's bundle root).
    # Externals (Discord, Google, …) install at runtime into the live dir (ADR 0058).
    ("plugins", "plugins"),
    # The published docs corpus — the `docs` plugin reads it (`docs/` beside the bundled
    # `plugins/` under _MEIPASS) to power docs_search/docs_read + the Docs view. Only the
    # Diátaxis sections + ADRs; `docs/dev` (internal) and `.vitepress` (build) are excluded.
    ("docs/tutorials", "docs/tutorials"),
    ("docs/guides", "docs/guides"),
    ("docs/reference", "docs/reference"),
    ("docs/explanation", "docs/explanation"),
    ("docs/adr", "docs/adr"),
]

# Packages PyInstaller's static analysis under-collects (dynamic imports +
# importlib.metadata entry points). --collect-all pulls modules + data + metadata.
COLLECT_ALL = [
    "langchain",
    "langchain_core",
    "langchain_openai",
    "langgraph",
    "ddgs",
    "langfuse",
    "croniter",
    # stdlib zoneinfo's fallback IANA database — Windows has no system tz data,
    # and zoneinfo imports tzdata DYNAMICALLY, so the import-scan misses it;
    # without the collect every ZoneInfo(...) in the frozen sidecar raised (#1683).
    "tzdata",
    # A2A 1.0 (ADR 0014): the SDK + the protoLabs conventions layer (git-dep).
    # Both pull submodules/metadata that a bare import-scan misses — without a
    # full collect, the frozen `protolabs_a2a` is missing `build_agent_card`.
    "a2a",
    "protolabs_a2a",
    # a2a-sdk[sqlite] durable task/push stores: imported lazily by the SDK, so
    # the import-scan misses them — collect explicitly.
    "aiosqlite",
    "sqlalchemy",
    # Comms-plugin runtime deps (ADR 0058): a plugin installed at runtime in the
    # frozen app can only import what's bundled. `websockets` is what the Discord /
    # Slack comms plugins use (httpx is already pulled by the core deps); `tools` is
    # the core tools package, collected whole because a plugin may import a core tool
    # module by file path (the import-scan misses those).
    "websockets",
    "tools",
    # MCP client (tools/mcp_tools) — connect external MCP servers; the SDK is lazily
    # imported, so collect it explicitly. (An external Google Gmail/Calendar MCP
    # plugin re-invokes the frozen binary via the generic ``--mcp-plugin <id>`` shim.)
    "mcp",
    # Markdown renderer for the bundled `docs` plugin's reader view — imported only by
    # the path-loaded plugin, so the import-scan misses it; collect explicitly.
    "markdown_it",
    # The pip-less wheel installer (ADR 0093) resolves deps with packaging.markers /
    # .specifiers / .requirements / .version at runtime in the frozen app. They're
    # imported lazily inside wheel_installer, so collect the whole package (+ its
    # vendored parser data) to be safe rather than rely on the import-scan.
    "packaging",
]

# Google client libraries (ADR 0017) — bundled only when installed in the build
# env (``requirements-google.txt``). Keeps a lean build (no google) working;
# install the extra to ship Gmail/Calendar in the frozen app.
OPTIONAL_COLLECT_ALL = [
    "google.auth",
    "google.oauth2",
    "google_auth_oauthlib",
    "googleapiclient",
]

# Document-generation stack (ADR 0092) — the knowledge-work baseline the desktop
# app ships ON by default so first-party skill packs (cowork's docx/xlsx/pptx/pdf
# skills) and plugins like protobanana (Pillow) actually produce files on the
# frozen runtime instead of hitting the ADR 0058 D2 "install on a server/Docker"
# refusal. Installed in CI from ``requirements-docs.txt``; a lean local freeze
# without it still works (find_spec-guarded, like the Google tier). ``--collect-all``
# is REQUIRED here — reportlab ships font/AFM data, python-docx/pptx ship their
# default .docx/.pptx templates as package data, and a bare import-scan misses all
# of it (the library raises at runtime opening its default template).
#
# Each entry is (import_name, distribution_name) — they DIFFER for the ones that matter
# (python-docx→``docx``, python-pptx→``pptx``, Pillow→``PIL``), and that gap is load-bearing:
# the ADR 0058 D2 gate checks a plugin's ``requires_pip`` with installer._importable, which
# tries ``importlib.metadata.version(<dist>)`` FIRST. So we ``--copy-metadata <dist>`` alongside
# ``--collect-all <import>`` — otherwise cowork's ``requires_pip: [python-docx, …]`` could still
# be refused on the frozen app even though ``import docx`` works, because the dist-info wasn't
# bundled. (lxml + PIL also arrive transitively, but naming them keeps a runtime-installed
# plugin's lazy ``import PIL`` — protobanana — importable when nothing else pulled it.)
DOC_COLLECT_ALL = [
    ("docx", "python-docx"),
    ("openpyxl", "openpyxl"),
    ("pptx", "python-pptx"),
    ("reportlab", "reportlab"),
    ("lxml", "lxml"),
    ("PIL", "pillow"),
]

# tkinter is GUI dead weight in a headless server and a freeze hazard — exclude it.
# (Gradio + the chat_ui module it backed were removed from the project entirely.)
EXCLUDE = ["tkinter"]

# CLI subcommand modules that `server/cli.py::dispatch` reaches ONLY via a dynamic
# `importlib.import_module(...)` string (the `_FORWARD` table) — e.g. Fleet ▸ Add Agent
# spawns `<frozen> plugin install <bundle>` → `import_module("graph.plugins.cli")`.
# PyInstaller's static import scan can't follow a string import, so without an explicit
# hidden-import each of these is ABSENT from the bundle and the verb dies with
# `ModuleNotFoundError` in the frozen app (#2136 — cowork create; also fleet/skills/
# runtime/operator-mcp, i.e. ACP). MUST stay in sync with `server.cli._FORWARD` — the
# test `test_sidecar_bundles_every_forwarded_cli_module` fails if a new verb is added
# without collecting it here. --hidden-import pulls the module + its static import chain.
CLI_FORWARD_MODULES = [
    "graph.plugins.cli",
    "graph.workspaces.cli",
    "graph.skills.cli",
    "graph.fleet.cli",
    "graph.config_explain",
    "graph.model_cli",
    "runtime.cli",
    "ops.cli",
    "server.knowledge_cli",
    "server.operator_mcp",
]


def target_triple() -> str:
    """Tauri names sidecars ``<bin>-<rustc-host-triple>``; match it."""
    out = subprocess.run(["rustc", "-Vv"], capture_output=True, text=True, check=True).stdout
    for line in out.splitlines():
        if line.startswith("host:"):
            return line.split(":", 1)[1].strip()
    raise SystemExit("could not determine rustc host triple (is rustc installed?)")


def main() -> None:
    triple = target_triple()
    work = REPO / "build" / "sidecar"
    sep = ";" if os.name == "nt" else ":"

    add_data: list[str] = []
    for src, dest in BUNDLED_DATA:
        if (REPO / src).exists():
            add_data += ["--add-data", f"{REPO / src}{sep}{dest}"]
        else:
            print(f"warning: bundled data missing, skipping: {src}", file=sys.stderr)

    collect: list[str] = []
    for pkg in COLLECT_ALL:
        collect += ["--collect-all", pkg]
    # Optional tiers: collect only what's importable in this build env, so a lean
    # freeze (extra not installed) still succeeds instead of erroring on a --collect
    # of a missing package.
    import importlib.util

    def _collect_if_present(pkgs: list[str], hint: str) -> None:
        for pkg in pkgs:
            if importlib.util.find_spec(pkg) is not None:
                collect.extend(["--collect-all", pkg])
            else:
                print(f"note: optional package not installed, skipping: {pkg} ({hint})",
                      file=sys.stderr)

    _collect_if_present(OPTIONAL_COLLECT_ALL, "install requirements-google.txt to ship Gmail/Calendar")
    # Doc stack: --collect-all the module AND --copy-metadata the distribution, so the ADR 0058
    # D2 gate's metadata-first check (installer._importable → metadata.version(<dist>)) resolves
    # in the frozen app despite the dist≠import name gap. Guarded on the import name being present
    # (a lean local freeze without requirements-docs.txt just skips the tier).
    for imp, dist in DOC_COLLECT_ALL:
        if importlib.util.find_spec(imp) is not None:
            collect.extend(["--collect-all", imp, "--copy-metadata", dist])
        else:
            print(f"note: optional package not installed, skipping: {imp} "
                  "(install requirements-docs.txt to ship the document-generation stack)",
                  file=sys.stderr)
    exclude: list[str] = []
    for mod in EXCLUDE:
        exclude += ["--exclude-module", mod]

    # Collect the dynamically-dispatched CLI modules (#2136) — the static scan misses them.
    hidden: list[str] = []
    for mod in CLI_FORWARD_MODULES:
        hidden += ["--hidden-import", mod]

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile", "--noconfirm", "--clean",
        "--name", NAME,
        "--distpath", str(work / "dist"),
        "--workpath", str(work / "build"),
        "--specpath", str(work),
        *exclude, *hidden, *add_data, *collect,
        # ADR 0023: server.py is now the `server` package; freeze its module
        # entry point. PyInstaller bundles the whole `server` package and the
        # `--add-data` assets land at _MEIPASS top level (server/_bundle_root
        # resolves there when frozen).
        str(REPO / "server" / "__main__.py"),
    ]
    print("running:", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=str(REPO))

    BINARIES_DIR.mkdir(parents=True, exist_ok=True)
    suffix = ".exe" if os.name == "nt" else ""
    built = work / "dist" / f"{NAME}{suffix}"
    dest = BINARIES_DIR / f"{NAME}-{triple}{suffix}"
    shutil.copy2(built, dest)
    os.chmod(dest, 0o755)
    print(f"\nsidecar -> {dest}")


if __name__ == "__main__":
    main()
